### ISSUE TITLE
How to route back?

### ISSUE THREAD

**Issue by glenhermanus** [Flutterando/routefly#10]
I'm using this for Flutter Web. I'm trying Routefly.pop, but it's blank and the url not change back

**Comment by glenhermanus** [comment]
Oh i use it on Flutter web, so i know that the URL doesn't change when i Routefly.pop

**Comment by glenhermanus** [comment]
i found something, when use Routefly.navigate somehow pop doesn't work. When use push, the URL doesn't get updated, but the pop works. When use pushNavigate, it will push and also change the URL, and the pop works, but somehow when pop, the URL doesn't change to previous.

**Comment by jacobaraujo7** [comment]
The pop only works when there is a page on the Stack. If you use navigation it only keeps one rotation on the stack, so pop won't work.
The way you want to get back is by accessing the window API (Javacript) that controls the browser. Maybe we'll think of something for the web, but remember that we have to find a way on other platforms too,
