### ISSUE TITLE
[Flutter Web]Cannot handle URL if contains query parameter

### ISSUE THREAD

**Issue by glenrynaldyhermanus** [Flutterando/routefly#14]
I have a page where i can pass a param using query parameters like this

`https://mydomain.com/store/catalog?store=myUniqueStoreName`

When i copy the URL and entered it on browser, my app won't accept the query params and the URL in browsers changed to

`https://mydomain.com/store/catalog`

Somehow i can't get the query params work, the `Routefly.query.params['store']` always returns Null. 

It only works if I navigate from another page using
`Routefly.navigate('https://mydomain.com/store/catalog?store=myUniqueStoreName')`

**Comment by jacobaraujo7** [comment]
Hello.
Could you provide us with a simple code example so I can check it on my machine?

**Comment by jacobaraujo7** [comment]
I gonna be close this issue right now, but you can open again. Thank you!
