### ISSUE TITLE
Erro ao tentar gerar rotas []

### ISSUE THREAD

**Issue by DesktopiMatheus** [Flutterando/routefly#2]
Fiquei interessado no package então criei um projeto novo e rodei os seguintes comandos

`dart run routefly --init`

após criar o projeto, criei as páginas e ao rodar o comando para gerar as páginas simplesmente não está gerando as rotas.

![image](https://github.com/Flutterando/routefly/assets/145611264/95547732-2c2d-49ae-b7df-e3b52aea2dae)
![image](https://github.com/Flutterando/routefly/assets/145611264/1d3d8d67-6e52-4122-9f2c-e5e399f1fd01)
![image](https://github.com/Flutterando/routefly/assets/145611264/ee033cda-568e-449d-8c87-d523154e1865)
![image](https://github.com/Flutterando/routefly/assets/145611264/1f28a794-ed99-4c84-b0e2-e21c8a203d84)
![image](https://github.com/Flutterando/routefly/assets/145611264/1d464daa-780b-40ae-84a0-13e0c54bdd7e)

Não tenho nenhum erro porém não cria as rotas

**Comment by DouglasValerio** [comment]
@DesktopiMatheus 
Vc precisa sufixar seus arquivos com `_page`
Se vc trocar o nome do seu arquivo de `configurations.dart` para `configurations_page.dart` deve funcionar.

Referência: doc do package no pub.dev:
![image](https://github.com/Flutterando/routefly/assets/16308684/137a47e2-8cd1-4cf4-838b-1a35816d4e24)

**Comment by jacobaraujo7** [comment]
@DesktopiMatheus  conseguiu resolver?
