### ISSUE TITLE
How can we perform nested navigation?

### ISSUE THREAD

**Issue by Cavin6080** [Flutterando/routefly#9]
I wanted to try this package in my production App but I needed deep link and nested navigation functionality in that. Thus I wanted to know how can we do the same in routefly?

**Comment by dchandrani** [comment]
Any update on this issue?

**Comment by jacobaraujo7** [comment]
Hello.
See the "RouteOutlet" part of the documentation.
Support for nested routes is done!
https://github.com/Flutterando/routefly?tab=readme-ov-file#layout-routeroutlet
